name: Deploy Azure WebApp Slot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch Name
        required: true
        default: main

      slot:
        description: Select Slot
        required: true
        type: choice
        options:
          - production
          - staging

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}

    steps:

    - name: Checkout Selected Branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Display Deployment Information
      run: |
        echo "Repository : ${{ github.repository }}"
        echo "Branch     : ${{ github.event.inputs.branch }}"
        echo "Slot       : ${{ github.event.inputs.slot }}"
        echo "Commit     : $GITHUB_SHA"

    - name: Inject Deployment Information
      shell: bash
      run: |

        DATE=$(date +"%d-%b-%Y %H:%M:%S UTC")
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

        sed -i "s|__REPOSITORY__|${{ github.repository }}|g" webapp2slots/index.html
        sed -i "s|__WEBAPP__|${WEBAPP_NAME}|g" webapp2slots/index.html
        sed -i "s|__BRANCH__|${{ github.event.inputs.branch }}|g" webapp2slots/index.html
        sed -i "s|__SLOT__|${{ github.event.inputs.slot }}|g" webapp2slots/index.html
        sed -i "s|__COMMIT__|${SHORT_SHA}|g" webapp2slots/index.html
        sed -i "s|__DATE__|${DATE}|g" webapp2slots/index.html

    - name: Show Updated HTML
      run: cat webapp2slots/index.html

    - name: Deploy to Production
      if: github.event.inputs.slot == 'production'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./webapp2slots

    - name: Deploy to Staging
      if: github.event.inputs.slot == 'staging'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: staging
        publish-profile: ${{ secrets.AZURE_WEBAPP_STAGING_PUBLISH_PROFILE }}
        package: ./webapp2slots

    - name: Deployment Complete
      run: |
        echo "========================================="
        echo "Deployment Successful"
        echo "Repository : ${{ github.repository }}"
        echo "Web App    : ${WEBAPP_NAME}"
        echo "Branch     : ${{ github.event.inputs.branch }}"
        echo "Slot       : ${{ github.event.inputs.slot }}"
        echo "Commit     : $GITHUB_SHA"
        echo "========================================="
